---
fontsize: 6pt
geometry: "left=1.25cm,right=1.25cm, top=0.75cm, bottom=0.75cm"
mainfont: Calibri Light
output:
  pdf_document:
    includes:
      in_header: header.tex
    keep_tex: FALSE
    latex_engine: xelatex
  html_document:
    df_print: paged
classoption: landscape
urlcolor: blue
---

\SetWatermarkText{DRAFT}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(knitr.table.format = 'latex', knitr.kable.NA = '')

#load chunks from r script
# knitr::read_chunk("AnnualReportChunks.R")


```


```{r secondtable, echo=FALSE, warning=FALSE, results='asis'}


t2 <- annual.tbl.first %>%
  select(-cap.method) %>%
  mutate(us.base.pre.cap = if_else(management.unit %in% c("Skagit", "Stillaguamish", "Snohomish", "Hood Canal", "US Strait JDF", "Quillayute", "Hoh", "Queets", "Grays Harbor"), us.pre.cap - cdn.pre.unused,  us.pre.cap)) %>%
  mutate(us.base.post.cap = if_else(management.unit %in% c("Skagit", "Stillaguamish", "Snohomish", "Hood Canal", "US Strait JDF", "Quillayute", "Hoh", "Queets", "Grays Harbor"), us.post.cap - cdn.post.unused,  us.post.cap)) %>%
  mutate(cdn.base.pre.cap = if_else(management.unit == "Interior Fraser", cdn.pre.cap - us.pre.unused, cdn.pre.cap))  %>%
  mutate(cdn.base.post.cap = if_else(management.unit == "Interior Fraser", cdn.post.cap - us.post.unused, cdn.post.cap))  %>%
  mutate_if(is.numeric, ~percent(.,accuracy = 0.1, suffix = "\\%")) %>%
  mutate(us.pre.cap = if_else(management.unit %in% c("Skagit", "Stillaguamish", "Snohomish", "Hood Canal", "US Strait JDF", "Quillayute", "Hoh", "Queets", "Grays Harbor"), paste(us.pre.cap, footnote_marker_symbol(3, "latex",), sep = " "), us.pre.cap )) %>%
  mutate(us.post.cap = if_else(management.unit %in% c("Skagit", "Stillaguamish", "Snohomish", "Hood Canal", "US Strait JDF", "Quillayute", "Hoh", "Queets", "Grays Harbor"), paste(us.post.cap, footnote_marker_symbol(3, "latex"), sep = " "), us.post.cap )) %>%
  mutate(cdn.pre.cap = if_else(management.unit == "Interior Fraser", paste(cdn.pre.cap, footnote_marker_symbol(3, "latex"), sep = " "), cdn.pre.cap)) %>%
  mutate(cdn.post.cap = if_else(management.unit == "Interior Fraser", paste(cdn.post.cap, footnote_marker_symbol(3, "latex"), sep = " "), cdn.post.cap)) %>%
  select(management.unit, us.base.pre.cap, everything()) %>%
  select(management.unit:us.pre.unused, us.base.post.cap, everything()) %>%
  select(management.unit:us.post.unused, cdn.base.pre.cap, everything()) %>%
  select(management.unit:cdn.pre.unused, cdn.base.post.cap, everything())


t2_us <- t2 %>%
  select(management.unit, us.base.pre.cap, cdn.pre.unused, us.pre.cap:us.pre.unused, us.base.post.cap, cdn.post.unused, us.post.cap:us.post.unused) %>%
  mutate(across(c(cdn.pre.unused, cdn.post.unused, us.pre.cap, us.post.cap),
         ~ case_when(management.unit == "Interior Fraser" ~ "", 
                     management.unit != "Interior Fraser" ~ .)))


t2_cdn <- t2 %>%
  select(management.unit, cdn.base.pre.cap, us.pre.unused, cdn.pre.cap:cdn.pre.unused, cdn.base.post.cap, us.post.unused, cdn.post.cap:cdn.post.unused) %>%
mutate(across(c(us.pre.unused, us.post.unused, cdn.pre.cap, cdn.post.cap),
         ~ case_when(management.unit != "Interior Fraser" ~ "", 
                     management.unit == "Interior Fraser" ~ .)))


# t2$us.pre.cap[5:13] <-  (paste0(t2$us.pre.cap[5:13], footnote_marker_symbol(2)))
# t2$us.post.cap[5:13] <- (paste0(t2$us.post.cap[5:13], footnote_marker_symbol(2)))
# t2$cdn.pre.cap[2] <- (paste0(t2$cdn.pre.cap[2], footnote_marker_symbol(2)))
# t2$cdn.post.cap[2] <- (paste0(t2$cdn.pre.cap[2], footnote_marker_symbol(2)))

cdn_skag_unused <- annual.tbl.first$cdn.pre.unused[annual.tbl.first$management.unit == "Skagit"] %>%
  percent(., accuracy = 0.1)

us_skag_cap <- annual.tbl.first$us.pre.cap[annual.tbl.first$management.unit == "Skagit"] %>%
  percent(., accuracy = 0.1)

footnote2 <- str_glue("Contains the treaty ER cap plus the unused portion of the intercepting party's ER. For example in the preseason, Skagit includes US share plus the unused {cdn_skag_unused} Canadian allocation, totalling {us_skag_cap} total US allocation.")

table2form_us <-  kable(t2_us, digits = 1,
                     col.names = c("Management unit", paste0("Cap", footnote_marker_symbol(2)),"CDN Unused", "Cap + Unused",  "Model", "Unused", paste0("Cap", footnote_marker_symbol(2)),"CDN Unused", "Cap + Unused",  "Model", "Unused"), escape = F, linesep = "", booktabs = T, format = "latex") %>%
  kable_styling(latex_options = c("hold_position", "scale_down")) %>%
  # column_spec(2, border_left = TRUE)%>%
  # column_spec(5, border_left = TRUE)%>%
  # column_spec(8, border_left = TRUE)%>%
  # column_spec(11, border_left = TRUE)%>%
  # column_spec(13, border_right  = TRUE)%>%
  row_spec(c(seq(1, nrow(t2),2)), background = "#d2d2d2") %>%
  add_header_above(c(" ", "Pre-Season" = 5, "Post-Season" = 5))%>%
  add_header_above(c(" ", "Exploitation Rate for Southern U.S.* Fisheries" = 10))
  # footnote(symbol = c("Southern U.S. is limited to US fisheries south of the Canadian border.", "ER Cap before the unused portion from the intercepting party is included.",  footnote2), threeparttable = T)


table2form_cdn <-  kable(t2_cdn, digits = 1,
                     col.names = c("Management unit", paste0("Cap", footnote_marker_symbol(2)),"US Unused", "Cap + Unused",  "Model", "Unused", paste0("Cap", footnote_marker_symbol(2)),"US Unused", "Cap + Unused",  "Model", "Unused"), escape = F, linesep = "", booktabs = T, format = "latex") %>%
  kable_styling(latex_options = c("hold_position", "scale_down")) %>%
  # column_spec(2, border_left = TRUE)%>%
  # column_spec(5, border_left = TRUE)%>%
  # column_spec(8, border_left = TRUE)%>%
  # column_spec(11, border_left = TRUE)%>%
  # column_spec(13, border_right  = TRUE)%>%
  row_spec(c(seq(1, nrow(t2),2)), background = "#d2d2d2") %>%
  add_header_above(c(" ", "Pre-Season" = 5, "Post-Season" = 5))%>%
  add_header_above(c(" ", "Exploitation Rate for Canadian Fisheries" = 10)) %>%
   footnote(symbol = c("Southern U.S. is limited to US fisheries south of the Canadian border.", "ER Cap before the unused portion from the intercepting party is included. See PST chapter 5 items 8 to 9",  footnote2), threeparttable = T) 




print(table2form_us)
print(table2form_cdn)



```
