---
title: "&nbsp;"
output:
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


#load chunks from r script
# knitr::read_chunk("AnnualReportChunks.R")


```

\newpage
\thispagestyle{empty}

<style>
.main-container {
  max-width: unset;
}
</style>

<!-- <p><b>Table 2: Exploitation rates by country for the `r run.year` return year.</b><p> -->
<!-- US Exploitation Rates: For US ER on Canadian Management Units (MU), a 10% ER Cap for Interior Fraser Coho is allowable under the PSC Coho agreement based on Low status. ER Caps are not defined for other Canadian MUs because status is not available. -->
<!-- Canadian Exploitation Rates: For Canadian ER Caps on US MUs, the pre-season ER Caps are the total allowable ER under the PSC Coho agreement. For Canadian ER Caps on Canadian MUs, a 10% ER Cap for Interior Fraser Coho is allowable under the PSC Coho agreement. -->
<!-- Pre-season ERs reflect combined US and Canadian pre-season planning processes and do not include estimates of impacts in Canadian freshwater fisheries. Pre-season unused ERs are the difference between the ER Caps and modelled values. Post-season ER Caps and unused ERs are comparable to pre-season values except that they are based on post-season cohort abundance and associated MU status. Post-season estimated ERs are generated from backwards Coho FRAM. *A negative value for unused ERs indicates that the post-season estimate exceeded the allowable ER Cap.* -->


```{r secondtable, echo=FALSE, warning=FALSE, results='asis'}


t2 <- annual.tbl.first %>%
  select(-cap.method) %>%
  mutate(us.base.pre.cap = if_else(management.unit %in% c("Skagit", "Stillaguamish", "Snohomish", "Hood Canal", "US Strait JDF", "Quillayute", "Hoh", "Queets", "Grays Harbor"), us.pre.cap - cdn.pre.unused,  us.pre.cap)) %>%
  mutate(us.base.post.cap = if_else(management.unit %in% c("Skagit", "Stillaguamish", "Snohomish", "Hood Canal", "US Strait JDF", "Quillayute", "Hoh", "Queets", "Grays Harbor"), us.post.cap - cdn.post.unused,  us.post.cap)) %>%
  mutate(cdn.base.pre.cap = if_else(management.unit == "Interior Fraser", cdn.pre.cap - us.pre.unused, cdn.pre.cap))  %>%
  mutate(cdn.base.post.cap = if_else(management.unit == "Interior Fraser", cdn.post.cap - us.post.unused, cdn.post.cap))  %>%
  mutate_if(is.numeric, ~percent(.,accuracy = 0.1)) %>%
  select(management.unit, us.base.pre.cap, everything()) %>%
  select(management.unit:us.pre.unused, us.base.post.cap, everything()) %>%
  select(management.unit:us.post.unused, cdn.base.pre.cap, everything()) %>%
  select(management.unit:cdn.pre.unused, cdn.base.post.cap, everything())



t2_us <- t2 %>%
  select(management.unit, us.base.pre.cap, cdn.pre.unused, us.pre.cap:us.pre.unused, us.base.post.cap, cdn.post.unused, us.post.cap:us.post.unused) %>%
  mutate(across(c(cdn.pre.unused, cdn.post.unused, us.pre.cap, us.post.cap),
         ~ case_when(management.unit == "Interior Fraser" ~ "", 
                     management.unit != "Interior Fraser" ~ .))) 

t2_cdn <- t2 %>%
  select(management.unit, cdn.base.pre.cap, us.pre.unused, cdn.pre.cap:cdn.pre.unused, cdn.base.post.cap, us.post.unused, cdn.post.cap:cdn.post.unused) %>%
mutate(across(c(us.pre.unused, us.post.unused, cdn.pre.cap, cdn.post.cap),
         ~ case_when(management.unit != "Interior Fraser" ~ "", 
                     management.unit == "Interior Fraser" ~ .)))


run.year.text <- paste0("**", as.character(run.year), "**")


t2_gt_us <- t2_us %>%
  gt() %>%
   tab_header(title = md(paste0('**Table 2: Exploitation rates by country for the** ', run.year.text, ' **return year.**
US Exploitation Rates: For US ER on Canadian Management Units (MU), a 10% ER Cap for Interior Fraser Coho is allowable under the PSC Coho agreement based on Low status. ER Caps are not defined for other Canadian MUs because status is not available.
Canadian Exploitation Rates: For Canadian ER Caps on US MUs, the pre-season ER Caps are the total allowable ER under the PSC Coho agreement. For Canadian ER Caps on Canadian MUs, a 10% ER Cap for Interior Fraser Coho is allowable under the PSC Coho agreement.
Pre-season ERs reflect combined US and Canadian pre-season planning processes and do not include estimates of impacts in Canadian freshwater fisheries. Pre-season unused ERs are the difference between the ER Caps and modelled values. Post-season ER Caps and unused ERs are comparable to pre-season values except that they are based on post-season cohort abundance and associated MU status. Post-season estimated ERs are generated from backwards Coho FRAM. *A negative value for unused ERs indicates that the post-season estimate exceeded the allowable ER Cap.*'))) %>%
  tab_spanner(label = 'Pre-Season', columns = us.base.pre.cap:us.pre.unused) %>%
  tab_spanner(label = 'Post-Season', columns = us.base.post.cap:us.post.unused) %>%
  tab_spanner('Exploitation Rate for Southern U.S.* Fisheries', management.unit:us.post.unused) %>%
  tab_options(table.width = 10) %>%
  sub_missing(missing_text = "") %>%
  cols_label(management.unit = 'Managment Unit', cdn.base.pre.cap		= md("Treaty Cap"))


t2_gt_cdn <- t2_cdn %>%
  gt() %>%
  tab_spanner(label = 'Pre-Season', columns = cdn.base.pre.cap:cdn.pre.unused ) %>%
  tab_spanner(label = 'Post-Season', columns = cdn.base.post.cap:cdn.post.unused) %>%
  tab_spanner('Exploitation Rate for Canadian Fisheries', management.unit:cdn.post.unused)%>%
  tab_options(table.width = 10, ) %>%
  sub_missing(missing_text = "") %>%
  cols_label(management.unit = 'Managment Unit', cdn.base.pre.cap		= md("Treaty Cap")) %>%
  tab_footnote(footnote = "*Southern U.S. is limited to US fisheries south of the Canadian border.")


t2_final <- gt_group(t2_gt_us, t2_gt_cdn) 

t2_final

# 
# print(t2_gt)



```
